#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()

local old = uci:get('network', 'wan', 'dns')
if type(old) == 'string' then
    old = {old}
end

if type(old) == 'table' and #old > 0 then
    local static = uci:get_first('gluon-wan-dnsmasq', 'static', 'server')

    if type(static) ~= 'table' or #static == 0 then
        uci:set_list('gluon-wan-dnsmasq', uci:get_first('gluon-wan-dnsmasq', 'static'), 'server', old)
        uci:save('gluon-wan-dnsmasq')
        uci:commit('gluon-wan-dnsmasq')
        uci:delete('network', 'wan', 'dns')
        uci:save('network')
        uci:commit('network')
    end
end
