#!/usr/bin/lua
-- Enables or disables SSIDs depending on
-- whether the gateway is reachable
uci = require("uci").cursor()

gateway   = "2a06:8782:ffbb:2018::7"
attempts  = 15
interval  = 30

function run()

  local reachable = false
  local enabled   = uci:get("wireless", "client_radio0", "disabled") ~= "1"

  -- Test reachability
  for i=1, attempts, 1 do
    if os.execute("ping -n -c1 -W1 "..gateway.." > /dev/null") == 0 then
      reachable = true
      break
    end
  end

  if reachable ~= enabled then
    print("state change to " ..  (reachable and 'reachable' or 'unreachable'))

    uci:foreach("wireless", "wifi-iface",
      function(s)
        -- node specific wifi
        if string.match(s['.name'], "^priv_") then
          uci:set("wireless", s['.name'], "disabled", reachable and '1' or '0')
        end

        -- wifi without encryption or management?
        if string.match(s['.name'], "^client_") then
          uci:set("wireless", s['.name'], "disabled", reachable and '0' or '1')
        end
    end)


    uci:save("wireless")
    os.execute("wifi")
  end

end


-- check on startup, if own interface is ready
local enabled   = uci:get("wireless", "client_radio0", "disabled") ~= "1"

uci:foreach("wireless", "wifi-iface",
	function(s)
		-- node specific wifi
		if string.match(s['.name'], "^priv_") then
			uci:set("wireless", s['.name'], "disabled", reachable and '1' or '0')
		end

		-- wifi without encryption or management?
		if string.match(s['.name'], "^client_") then
			uci:set("wireless", s['.name'], "disabled", reachable and '0' or '1')
		end
end)
uci:save("wireless")
os.execute("wifi")

-- start watchdog
while true do
  run()
  os.execute("sleep " .. interval)
end
