#!/usr/bin/lua

local site = require 'gluon.site_config'
local uci = require 'luci.model.uci'

local c = uci.cursor()

if c:get('autoupdater', 'settings') and c:get('autoupdater', 'settings', 'last_autochange') ~= site.autoupdater_switcher.date then
    c:set('autoupdater', 'settings', 'branch', site.autoupdater_switcher.branch)
    c:set('autoupdater', 'settings', 'last_autochange', site.autoupdater_switcher.date)
    c:save('autoupdater')
    c:commit('autoupdater')
end
