#!/usr/bin/lua

local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()

local function configure_client(radio, index, suffix)
  local hwmode = uci:get('wireless', radio, 'hwmode')
  uci:set('wireless', radio, 'txpower', 0)
  if hwmode == '11g' or hwmode == '11ng' then
    uci:set('wireless', radio, 'supported_rates', '6000 9000 12000 18000 24000 36000 48000 54000')
    uci:set('wireless', radio, 'basic_rate', '6000 9000 18000 36000 54000')
  end
  local client = 'client_' .. radio
  if uci:get('wireless', client) then
    uci:set('wireless', client, 'maxassoc', 60)
    uci:set('wireless', client, 'isolate', 1)
    uci:set('wireless', client, 'disabled', 1)
  end
end

local function configure_radio(radio, index, _)
  local suffix = radio:match('^radio(%d+)$')
  configure_client(radio, index, suffix)
end

util.iterate_radios(configure_radio)

uci:save('wireless')
