#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()

uci:delete_all('network', 'switch_vlan')
uci:section('network', 'switch_vlan', 'mgmt_vlan', {
    vlan = 2,
    ports = '0t 1 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'client_vlan', {
    vlan = 1,
    ports = '0t 1t 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'generic_vlan1', {
    vlan = 11,
    ports = '1t 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'generic_vlan2', {
    vlan = 12,
    ports = '1t 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'generic_vlan3', {
    vlan = 13,
    ports = '1t 2t 3t 4t 5t',
    device = 'switch0',
})

-- Set PVID
uci:delete_all('network', 'switch_port')
for i=0, 6, 1 do
    uci:section('network', 'switch_port', 'port_' .. i, {
        pvid = 1,
        port = i,
    })
end


uci:save('network')
