#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()

uci:delete_all('network', 'switch_vlan')

-- Client VLAN=3
uci:set('network', 'client', 'ifname', 'eth0.3')

-- Native VLAN
uci:section('network', 'switch_vlan', 'vlan_1', {
    vlan = 1,
    ports = '0t 1 2 3 4 5',
    device = 'switch0',
})

-- Other VLANs
for i=2, 13, 1 do
    uci:section('network', 'switch_vlan', 'vlan_' .. i, {
        vlan = i,
        ports = '0t 1t 2t 3t 4t 5t',
        device = 'switch0',
    })
end

-- Set PVID for ports
uci:delete_all('network', 'switch_port')
for i=0, 6, 1 do
    uci:section('network', 'switch_port', 'port_' .. i, {
        pvid = 1,
        port = i,
    })
end


uci:save('network')
