#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local util = require 'gluon.util'

uci:delete_all('network', 'switch_vlan')
uci:section('network', 'switch_vlan', 'mgmt_vlan', {
    vlan = 2,
    ports = '0t 1 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'client_vlan', {
    vlan = 1,
    ports = '0t 1t 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'generic_vlan1', {
    vlan = 11,
    ports = '1t 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'generic_vlan2', {
    vlan = 12,
    ports = '1t 2t 3t 4t 5t',
    device = 'switch0',
})
uci:section('network', 'switch_vlan', 'generic_vlan3', {
    vlan = 13,
    ports = '1t 2t 3t 4t 5t',
    device = 'switch0',
})
uci:set('network', 'wan', 'peerdns', 1)
uci:save('network')
uci:commit('network')

uci:set('alfred', 'alfred', 'start_vis', '0')
uci:delete('alfred', 'alfred', 'batmanif')
uci:save('alfred')
uci:commit('lldpd')

local function accept_input_on_wan(zone)
    if zone.name == 'wan' then
        uci:set('firewall', zone['.name'], 'input', 'ACCEPT')
        uci:set('firewall', zone['.name'], 'conntrack', '0')
    end

    return true
end
uci:foreach('firewall', 'zone', accept_input_on_wan)
local function accept_icmpv6_on_client(rule)
    if rule.name == 'Allow-ICMPv6-Input' then
        uci:set('firewall', rule['.name'], 'src', 'client')
    end

    return true
end
uci:foreach('firewall', 'rule', accept_icmpv6_on_client)
uci:section('firewall', 'rule', 'client_alfred', {
    name = 'client_alfred',
    src = 'client',
    dest_port = '16962',
    proto = 'udp',
    target = 'ACCEPT',
})
uci:save('firewall')
uci:commit('firewall')
