#!/bin/sh

set -e

for var in share_location latitude longitude; do
    # only copy config values if old ones exist and new ones dont'
    if [ -n "$(uci get gluon-location.@location[0].$var|tr -d .0)" -o \
        -z "$(uci get system.@system[0].$var|tr -d .0)" ]; then
        continue
    fi
    uci set "gluon-location.@location[0].$var=$(uci get system.@system[0].$var)"
    uci del "system.@system[0].$var"
done
uci commit
