#!/usr/bin/lua

local util = require 'gluon.util'

local uci = require('simple-uci').cursor()

local function configure_mgmt(radio, index, suffix)

  uci:delete('wireless', 'priv_' .. radio)
  uci:section('wireless', 'wifi-iface', 'priv_' .. radio, {
      device = radio,
      network = 'client',
      mode = 'ap',
      ssid = '' .. gluon.util.node_id(),
      macaddr = util.generate_mac(7, index-1),
      ifname = 'priv' .. suffix,
      disabled = 1,
      hidden = 0,
      encryption = 'psk2',
      key = 'himmlisch',
  })
end

local function configure_radio(radio, index, _)
  local suffix = radio:match('^radio(%d+)$')
  local hwmode = uci:get('wireless', radio, 'hwmode')
  if hwmode == '11a' or hwmode == '11na' then
    configure_mgmt(radio, index, suffix)
  end
end

util.iterate_radios(uci, configure_radio)

uci:save('wireless')
