#!/usr/bin/lua

local util = require 'gluon.util'

local uci = require('simple-uci').cursor()

local function configure_mgmt(radio, index, suffix)

  uci:delete('wireless', 'priv_' .. radio)
  uci:section('wireless', 'wifi-iface', 'priv_' .. radio, {
      device = radio,
      network = 'client',
      mode = 'ap',
      ssid = 'offline-' .. gluon.util.node_id(),
      macaddr = util.generate_mac(7, index-1),
      ifname = 'priv' .. suffix,
      disabled = 1,
      hidden = 0,
  })
end

local function configure_radio(radio, index, _)
  local suffix = radio[".name"]:match('^radio(%d+)$')
  configure_mgmt(radio[".name"], index, suffix)
end

util.foreach_radio(uci, configure_radio)

uci:save('wireless')
