#!/usr/bin/lua

local util = require 'gluon.util'

local uci = require('simple-uci').cursor()

local function configure_client(radio, index, suffix)
  uci:set('wireless', radio, 'txpower', 0)
  local client = 'client_' .. radio
  if uci:get('wireless', client) then
    uci:set('wireless', client, 'maxassoc', 60)
    uci:set('wireless', client, 'isolate', 1)
    uci:set('wireless', client, 'disabled', 1)
  end
end

local function configure_radio(radio, index, _)
  local suffix = radio[".name"]:match('^radio(%d+)$')
  configure_client(radio[".name"], index, suffix)
end

util.foreach_radio(uci, configure_radio)

uci:save('wireless')
