#!/usr/bin/lua

local platform_info = require('platform_info')
local uci = require('simple-uci').cursor()
local util = require 'gluon.util'

if string.match(platform_info.get_image_name(), "archer%-c7") or string.match(platform_info.get_image_name(), "tl%-wdr") then
  uci:set('network','@switch_vlan[0]','ports','5 0t')

  uci:delete('network', 'switch_mesh2')
  uci:delete('network', 'switch_mesh3')
  uci:delete('network', 'switch_mesh4')

  uci:section('network', 'switch_vlan', 'switch_mesh2', {
    device = 'switch0',
    vlan = '3',
    ports = '4 0t',
  })
  uci:section('network', 'switch_vlan', 'switch_mesh3', {
    device = 'switch0',
    vlan = '4',
    ports = '3 0t',
  })
  uci:section('network', 'switch_vlan', 'switch_mesh4', {
    device = 'switch0',
    vlan = '5',
    ports = '2 0t',
  })


  uci:delete('network', 'mesh_lan2')
  uci:delete('network', 'mesh_lan3')
  uci:delete('network', 'mesh_lan4')
  uci:section('network', 'interface', 'mesh_lan2', {
    ifname = 'eth1.3',
    proto = 'gluon_wired',
    igmp_snooping = '0',
    index = '5',
    disabled ='0',
    transitive = '1',
    macaddr=uci:get('network','meshlan','macaddr'),
  })
  uci:section('network', 'interface', 'mesh_lan3', {
    ifname = 'eth1.4',
    proto = 'gluon_wired',
    index = '6',
    igmp_snooping = '0',
    disabled ='0',
    transitive = '1',
    macaddr=uci:get('network','meshlan','macaddr'),
  })
  uci:section('network', 'interface', 'mesh_lan4', {
    ifname = 'eth1.5',
    index = '7',
    proto = 'gluon_wired',
    igmp_snooping = '0',
    disabled ='0',
    transitive = '1',
    macaddr=uci:get('network','meshlan','macaddr'),
  })

  uci:save('network')
end
