#!/usr/bin/lua

local uci = require('simple-uci').cursor()
local model = require('platform_info').get_model()
local models = {}

models["TP-Link TL-WDR3600 v1"] = function()
  -- Switch Ports:
  -- 0 CPU
  -- 1 WAN
  -- 2 LAN1
  -- 3 LAN2
  -- 4 LAN3
  -- 5 LAN4
  -- 6 unknown
  uci:set('network', 'client', 'ifname', 'eth0.3')
end

models["TP-Link Archer C7 v2"] = function()
  -- Switch Ports:
  -- 0 eth1
  -- 1 WAN
  -- 2 LAN1
  -- 3 LAN2
  -- 4 LAN3
  -- 5 LAN4
  -- 6 eth0
  uci:set('network', 'client', 'ifname', 'eth1.3')
end


local action = models[model]
if not action then
  print("unsupported model: '" .. model .. "'")
  os.exit(1)
end

uci:delete_all('network', 'switch_vlan')
action()

-- Native VLAN
uci:section('network', 'switch_vlan', 'vlan_1', {
    vlan = 1,
    ports = '0 1 2 3 4 5 6',
    device = 'switch0',
})

-- Other VLANs
for i=2, 13, 1 do
    uci:section('network', 'switch_vlan', 'vlan_' .. i, {
        vlan = i,
        ports = '0t 1t 2t 3t 4t 5t',
        device = 'switch0',
    })
end

-- Set PVID for ports
uci:delete_all('network', 'switch_port')
for i=0, 6, 1 do
    uci:section('network', 'switch_port', 'port_' .. i, {
        pvid = 1,
        port = i,
    })
end

uci:save('network')
