#!/bin/sh /etc/rc.common

START=05

start() {

    echo "reghack!"
    REGHACK=/lib/wifi/reghack.mips.elf

    # Install regdomain hack
    if [ ! -f /etc/.regd ]; then
        $REGHACK /lib/modules/*/ath.ko
        $REGHACK /lib/modules/*/cfg80211.ko
        touch /etc/.regd
    fi
}
