#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /sbin/watchdog
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_close_instance
}
